name: Deploy to  max app to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install aws-cdk.core
        pip install aws-cdk.aws-ec2
        pip install aws-cdk.aws-eks
        pip install aws-cdk.aws-elasticloadbalancingv2
        pip install aws-cdk.aws-iam

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
      run: |
        cdk deploy --require-approval never
